---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false #"{{ molecule_no_log }}"
  tasks:
    # Developer must implement.

    # Developer must map instance config.
    # Mandatory configuration for Molecule to function.
    - name: server configuration
      set_fact:
        server_conf: {
          'instance': 'windows',
          'address':  'http://18.207.168.35:5985/wsman',
          'user': 'Administrator',
          'port': '5985'}
      register: server
    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instance }}",
          'address': "{{ item.address }}",
          'user': "{{ item.user }}",
          'port': "{{ item.port }}"}
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
